=== juliaHrabovska/webStore/src/main/webapp/WEB-INF/security.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="security">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="rule">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="url" type="xs:string" />
							<xs:element maxOccurs="unbounded" name="role" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== juliaHrabovska/webStore/src/main/webapp/WEB-INF/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<security xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="security.xsd">
	<rule>
		<url>/makeOrder</url>
		<role>1</role>
	</rule>
	<rule>
		<url>/showCart</url>
		<role>1</role>
	</rule>
	<rule>
		<url>/successOrder</url>
		<role>1</role>
	</rule>
</security>
